### ISSUE TITLE
[Question] how to create a proxy from host into a k8s service?

### ISSUE THREAD

**Issue by davidpelfree** [unboundedsystems/k3s-dind#7]
Hi.

First, thanks for this `k3s-dind` tool! It really works good out of the box, even on CentOS 7 with default formatted XFS, where containerd has issues.

Now for my issue:

I am trying to expose k8s service on the host as an HTTP port.

here's my configuration:

I have a single-node cluster with IP `172.16.1.1` which I have ran `docker run ... unboundedsystems/k3s-dind` on it.

I followed [this example](http://docs.heptio.com/content/tutorials/aws-qs-helm-wordpress.html) to create a running Wordpress site using Helm.

Running `kubectl get svc -n varmywordpress` gives:
```
NAME                TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
wordpress-mariadb   ClusterIP      10.43.215.71   <none>        3306/TCP                     51m
wordpress           LoadBalancer   10.43.1.30     10.10.128.2   80:31470/TCP,443:30716/TCP   51m

```

So I have port `80` opened on Docker network (in my case, Docker's IP range is `10.10.x.x` so the service IP is: `10.10.128.2`).
It seems to work from the host, if I do: `curl 10.10.128.2`.

However, the network `10.10.x.x` is an internal Docker network which is accessible only from the host.

I am trying to open a port on the host to expose this Wordpress service to the corporate LAN.

I can access the service from my laptop using: `http://localhost:8001/api/v1/namespaces/varmywordpress/services/wordpress:80/proxy/`.

However, using the proxy URL is good for debugging, not to publish the service to the world.

Since this `k3s-dind` project has its internal Docker (which has its own pros like better security by not exposing host's `/var/run/docker.sock` to containers), I cannot tell internal Docker to expose a port on the host

So my question is **how to create a proxy on the host, that is mapped to the required service**?

Maybe Nginx/Traefik running on the host may help here, if they automatically identify k8s services and expose them (maybe using labels/annotations on the k8s service to tell what port do we want, as done in Traefik with "Docker provider")

**Comment by mterrel** [comment]
@davidpelfree It's great to hear that you like `k3s-dind`! I'm glad you're finding it useful.

So first, just to make sure I understand your question, I'll rephrase it. Please correct anything I get wrong here:  You have a host system and you'd like to make that host system serve Wordpress publicly/externally on port 80 and 443 and you'd like to use `k3s-dind` to do that.

If I got that right, I think it may be as simple as adding `-p 80:80 -p 443:443` to your `docker run` command line for `k3s-dind`, like this:

```bash
docker run -d --privileged --name k3s --hostname k3s -p 8443:8443 -p 80:80 -p 443:443 unboundedsystems/k3s-dind
```

Let me know if that works for you or if I'm mistaken about what you're trying to do. If that didn't work for you, please also give me the exact `docker run` command line you used to run `k3s-dind`.

**Comment by davidpelfree** [comment]
@mterrel  thanks for the quick response.

Wordpress is just an example. 

Of course if you know the **static** port addresses the solution is trivial.

My question is how to **dynamically** open a port which we don't know its number beforehand. 

Think, for example. about a dev machine which runs a bunch of micro-services, and developer want to access them from his laptop. You don't want to limit yourself to predefined ports, but to be able to open **ANY** port, as done in Docker / Compose / Swarm.

Maybe using `--network host` when running `docker run ... k3s-dind` may help. I have to check this.

**Comment by mterrel** [comment]
@davidpelfree Ah, yes, that's a much harder problem. Yes, adding `--network=host` to the `docker run` for `k3s-dind` should do what you want. However, that approach may expose much more than you want and therefore has some security implications. For a locked-down network used for dev, that may be ok, but please use with caution.

Unfortunately, I know of no simple way to solve this for `k3s-dind` in a more secure way that also only opens specific dynamic ports on the host's external IP. As far as I know, you'd need to do an additional integration with k8s/k3s, like you mentioned with either a load balancer (Nginx/Traefik) or maybe with Linux's firewall.

**Comment by davidpelfree** [comment]
To summarize, I came into this solution:

1. I run `docker run ... k3s-dind` with 3 port mappings: 8443 (TLS ingress), 8080 (HTTP ingress) and 6000 (k8s API / management, based on PR #9 ).
2. I run Ingress service in the cluster, deployed as "LoadBalancer", so it exposes ports 8080 and 8443 to the Docker network, and as a result of (1) above, these ports are available at the host level
3. I have a corporate firewall allowing only HTTPS ingress traffic on port 8443 to the host, so ports 8080 and 6000 (for the k8s API) are accessible only from the host, or by using an SSH tunnel.
4. Using the Ingress from (2) above, it's now easy to access various services running on the cluster, not by using many TCP ports, but by using multiple virtual-hosts and proxy-paths. This is were Ingress comes into the picture.

So there's no need any more to open dynamically unknown number of ports as I thought at the beginning. So I close this issue.

**Comment by mterrel** [comment]
Thanks for the thorough follow-up info @davidpelfree!
